=== kararia/ivion-cards-json/schema/card_schema.json
{
    "$id": "https://github.com/kararia/ivion-cards-json/blob/master/schema/card_schema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "oneOf": [
        {
            "properties": {
                "type_code": {
                    "const": "skill"
                }
            },
            "required": [
                "action_cost",
                "power_cost",
                "heroic",
                "keywords"
            ]
        },
        {
            "properties": {
                "type_code": {
                    "const": "feat"
                }
            },
            "required": [
                "feat"
            ]
        },
        {
            "properties": {
                "type_code": {
                    "const": "relic"
                }
            },
            "required": [
                "relic"
            ]
        },
        {
            "properties": {
                "type_code": {
                    "const": "identity"
                }
            },
            "required": [
                "health_points",
                "minimum_deck_size"
            ]
        }
    ],
    "properties": {
        "action_cost": {
            "oneOf": [
                {
                    "type": "integer"
                },
                {
                    "type": "null"
                }
            ]
        },
        "code": {
            "pattern": "^[0-9]{5}$",
            "type": "string"
        },
        "col1": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "null"
                }
            ]
        },
        "col2": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "null"
                }
            ]
        },
        "deck_limit": {
            "oneOf": [
                {
                    "minimum": 0,
                    "type": "integer"
                },
                {
                    "type": "null"
                }
            ]
        },
        "disarm": {
            "oneOf": [
                {
                    "default": false,
                    "type": "boolean"
                },
                {
                    "type": "null"
                }
            ]
        },
        "faction_code": {
            "minLength": 1,
            "type": "string"
        },
        "feat": {
            "oneOf": [
                {
                    "default": false,
                    "type": "boolean"
                },
                {
                    "type": "null"
                }
            ]
        },
        "flavor": {
            "minLength": 0,
            "type": "string"
        },
        "health_points": {
            "oneOf": [
                {
                    "minimum": 0,
                    "type": "integer"
                },
                {
                    "type": "null"
                }
            ]
        },
        "heroic": {
            "oneOf": [
                {
                    "default": false,
                    "type": "boolean"
                },
                {
                    "type": "null"
                }
            ]
        },
        "illustrator": {
            "pattern": ".+",
            "type": "string"
        },
        "keywords": {
            "minLength": 1,
            "type": "string"
        },
        "minimum_deck_size": {
            "minimum": 40,
            "type": "integer"
        },
        "pack_code": {
            "maxLength": 5,
            "minLength": 2,
            "type": "string"
        },
        "position": {
            "minimum": 1,
            "type": "integer"
        },
        "power_cost": {
            "oneOf": [
                {
                    "type": "integer"
                },
                {
                    "type": "null"
                }
            ]
        },
        "quantity": {
            "minimum": 1,
            "type": "integer"
        },
        "range": {
            "oneOf": [
                {
                    "minimum": 0,
                    "type": "integer"
                },
                {
                    "type": "null"
                }
            ]
        },
        "relic": {
            "oneOf": [
                {
                    "default": false,
                    "type": "boolean"
                },
                {
                    "type": "null"
                }
            ]
        },
        "side_code": {
            "minLength": 1,
            "type": "string"
        },
        "silence": {
            "oneOf": [
                {
                    "default": false,
                    "type": "boolean"
                },
                {
                    "type": "null"
                }
            ]
        },
        "slow": {
            "oneOf": [
                {
                    "default": false,
                    "type": "boolean"
                },
                {
                    "type": "null"
                }
            ]
        },
        "text": {
            "minLength": 1,
            "type": "string"
        },
        "title": {
            "minLength": 1,
            "type": "string"
        },
        "type_code": {
            "minLength": 1,
            "type": "string"
        },
        "uniqueness": {
            "type": "boolean"
        }
    },
    "required": [
        "code",
        "faction_code",
        "deck_limit",
        "pack_code",
        "position",
        "quantity",
        "side_code",
        "title",
        "type_code",
        "uniqueness"
    ],
    "type": "object"
}

=== kararia/ivion-cards-json/pack/cal1.json
[
    {
        "action_cost": -1,
        "code": "00001",
        "deck_limit": 3,
        "disarm": true,
        "faction_code": "knight",
        "flavor": "Chastise the guilty once, and they may listen. Again, and they will surely scowl.",
        "heroic": null,
        "illustrator": "Wasan Techawibulchai",
        "keywords": "Ability",
        "pack_code": "cal1",
        "position": 1,
        "power_cost": 1,
        "quantity": 3,
        "range": 2,
        "side_code": "corp",
        "silence": null,
        "slow": null,
        "text": "{Silence 3} [i] target {Uncontrolled} opponent.",
        "title": "Chastise",
        "type_code": "skill",
        "uniqueness": false
    },
    {
        "action_cost": 0,
        "code": "00002",
        "deck_limit": 3,
        "disarm": true,
        "faction_code": "knight",
        "flavor": "My blade shall not run red for the likes of you.",
        "heroic": null,
        "illustrator": "Alexandra Schastlivaya",
        "keywords": "Ability",
        "pack_code": "cal1",
        "position": 2,
        "power_cost": -2,
        "quantity": 3,
        "range": null,
        "side_code": "corp",
        "silence": true,
        "slow": null,
        "text": "Draw a card for each {Attack} card you've resolved this turn. Become {Chivalrous} [c].",
        "title": "Clean thy Blade",
        "type_code": "skill",
        "uniqueness": false
    },
    {
        "action_cost": -1,
        "code": "00003",
        "deck_limit": 3,
        "disarm": null,
        "faction_code": "knight",
        "flavor": "Knights have been called unwise. Stupid. But never coward.",
        "heroic": true,
        "illustrator": "Septimius Ferdian",
        "keywords": "Attack",
        "pack_code": "cal1",
        "position": 3,
        "power_cost": 1,
        "quantity": 3,
        "range": 1,
        "side_code": "corp",
        "silence": null,
        "slow": null,
        "text": "Deal 4 damage to target enemy. {Stun} them. <(They lose a resource of their choice.)>",
        "title": "Daring Strike",
        "type_code": "skill",
        "uniqueness": false
    },
    {
        "action_cost": -1,
        "code": "00004",
        "deck_limit": 3,
        "disarm": null,
        "faction_code": "knight",
        "flavor": "Are you worthy of the Lady's blessing?",
        "heroic": null,
        "illustrator": "Dario Marzadori",
        "keywords": "Ability",
        "pack_code": "cal1",
        "position": 4,
        "power_cost": 1,
        "quantity": 3,
        "range": 2,
        "side_code": "corp",
        "silence": true,
        "slow": null,
        "text": "{Attach} to target empty tile. At the start of your turn, you may make a tile near {Enchanted Lake} {Enchanted Terrain} [et].",
        "title": "Enchanted Lake",
        "type_code": "skill",
        "uniqueness": false
    },
    {
        "action_cost": -1,
        "code": "00005",
        "deck_limit": 3,
        "disarm": true,
        "faction_code": "knight",
        "flavor": "And thus, his strike rang throughout the land, never to be forgotten.",
        "heroic": null,
        "illustrator": "Leo Aveiro",
        "keywords": "Attack",
        "pack_code": "cal1",
        "position": 5,
        "power_cost": 1,
        "quantity": 3,
        "range": 1,
        "side_code": "corp",
        "silence": true,
        "slow": null,
        "text": "Deal 5 damage to target enemy. Make a tile near you {Enchanted Terrain} [et].",
        "title": "Enchanted Strike",
        "type_code": "skill",
        "uniqueness": false
    },
    {
        "action_cost": 0,
        "code": "00006",
        "deck_limit": 3,
        "disarm": null,
        "faction_code": "knight",
        "flavor": "There is a pride in Calbrians that transcends wealth or glory.",
        "heroic": null,
        "illustrator": "Septimius Ferdian",
        "keywords": "Ability",
        "pack_code": "cal1",
        "position": 6,
        "power_cost": -1,
        "quantity": 3,
        "range": null,
        "side_code": "corp",
        "silence": true,
        "slow": null,
        "text": "You may play a card for 1 less [a]. <(This can't reduce the action cost of that card to 0.)>",
        "title": "For the King",
        "type_code": "skill",
        "uniqueness": false
    },
    {
        "action_cost": -2,
        "code": "00007",
        "deck_limit": 3,
        "disarm": true,
        "faction_code": "knight",
        "flavor": "Have your wits about you, for battle commences!",
        "heroic": null,
        "illustrator": "Wasan Techawibulchai",
        "keywords": "Attack",
        "pack_code": "cal1",
        "position": 7,
        "power_cost": 2,
        "quantity": 3,
        "range": 1,
        "side_code": "corp",
        "silence": null,
        "slow": null,
        "text": "Deal 7 damage to target enemy. Become {Chivalrous} [c].",
        "title": "Have At Thee",
        "type_code": "skill",
        "uniqueness": false
    },
    {
        "action_cost": 0,
        "code": "00008",
        "deck_limit": 3,
        "disarm": true,
        "faction_code": "knight",
        "flavor": "The darkest hour comes just before the dawn.",
        "heroic": null,
        "illustrator": "Septimius Ferdian",
        "keywords": "Ability",
        "pack_code": "cal1",
        "position": 8,
        "power_cost": -2,
        "quantity": 3,
        "range": null,
        "side_code": "corp",
        "silence": null,
        "slow": null,
        "text": "{Attach} to yourself until your next turn. If you would take damage, instead prevent that damage and put that many cards from your deck into your discard.",
        "title": "Have Faith",
        "type_code": "skill",
        "uniqueness": false
    },
    {
        "action_cost": -1,
        "code": "00009",
        "deck_limit": 3,
        "disarm": null,
        "faction_code": "knight",
        "flavor": "There are holy sites in Calbria where it is said that no lies may be told.",
        "heroic": null,
        "illustrator": "Dario Marzadori",
        "keywords": "Ability",
        "pack_code": "cal1",
        "position": 9,
        "power_cost": 1,
        "quantity": 3,
        "range": 2,
        "side_code": "corp",
        "silence": true,
        "slow": null,
        "text": "Make two target tiles {Enchanted Terrain} [et]. Draw a card.",
        "title": "Holy Ground",
        "type_code": "skill",
        "uniqueness": false
    },
    {
        "action_cost": 0,
        "code": "00010",
        "deck_limit": 3,
        "disarm": null,
        "faction_code": "knight",
        "flavor": "To be in the presence of a knight is to experience humility.",
        "heroic": null,
        "illustrator": "Septimius Ferdian",
        "keywords": "Ability",
        "pack_code": "cal1",
        "position": 10,
        "power_cost": -1,
        "quantity": 3,
        "range": 2,
        "side_code": "corp",
        "silence": true,
        "slow": null,
        "text": "Choose one: - {Destroy} target card. - Each player discards down to four cards.",
        "title": "Humble",
        "type_code": "skill",
        "uniqueness": false
    },
    {
        "action_cost": -1,
        "code": "00011",
        "deck_limit": 3,
        "disarm": null,
        "faction_code": "knight",
        "flavor": "The Lady watches diligently through the eyes of her chosen.",
        "heroic": null,
        "illustrator": "Wasan Techawibulchai",
        "keywords": "Ability",
        "pack_code": "cal1",
        "position": 11,
        "power_cost": 2,
        "quantity": 3,
        "range": 2,
        "side_code": "corp",
        "silence": true,
        "slow": null,
        "text": "{Attach} to target opponent. After they dishonor the code of {Chivalry}, deal 2 damage to them.",
        "title": "Judgment",
        "type_code": "skill",
        "uniqueness": false
    },
    {
        "action_cost": -2,
        "code": "00012",
        "deck_limit": 3,
        "disarm": true,
        "faction_code": "knight",
        "flavor": "No wrong shall go unrighted! No darkness shall persist undone!",
        "heroic": null,
        "illustrator": "Wojciech Depczy≈Ñski",
        "keywords": "Attack",
        "pack_code": "cal1",
        "position": 12,
        "power_cost": -2,
        "quantity": 3,
        "range": 1,
        "side_code": "corp",
        "silence": null,
        "slow": null,
        "text": "Deal 10 damage to target enemy. If you're {Chivalrous}, {Slow 2} [o] and {Silence 2} [i] them.",
        "title": "Justice",
        "type_code": "skill",
        "uniqueness": false
    },
    {
        "action_cost": -2,
        "code": "00013",
        "deck_limit": 3,
        "disarm": null,
        "faction_code": "knight",
        "flavor": "On this hallowed day, the Lady will find a new champion.",
        "heroic": null,
        "illustrator": "Septimius Ferdian",
        "keywords": "Ability",
        "pack_code": "cal1",
        "position": 13,
        "power_cost": 2,
        "quantity": 3,
        "range": null,
        "side_code": "corp",
        "silence": true,
        "slow": null,
        "text": "Gain a random {Relic}. If you've already gained a {Relic} this game, instead deal 5 damage to each opponent.",
        "title": "Light of Dawn",
        "type_code": "skill",
        "uniqueness": false
    },
    {
        "action_cost": -1,
        "code": "00014",
        "deck_limit": 3,
        "disarm": null,
        "faction_code": "knight",
        "flavor": "Even the wicked are compelled to work no treachery in its shadow.",
        "heroic": null,
        "illustrator": "Dario Marzadori",
        "keywords": "Ability",
        "pack_code": "cal1",
        "position": 14,
        "power_cost": 1,
        "quantity": 3,
        "range": 2,
        "side_code": "corp",
        "silence": true,
        "slow": null,
